owner: tracklab-tech
repo: status

sites:
  - name: Application
    url: https://app.tracklab.co/app/api/health
  - name: API
    url: https://app.tracklab.co/api/
  - name: Portail fournisseurs
    url: https://portal.tracklab.co/app/api/health
  - name: Site web
    url: https://www.tracklab.co
  - name: Test alerte
    url: https://status.tracklab.co/introuvable-pour-test

assignees:
  - quentinfapdepr

status-website:
  cname: status.tracklab.co
  logoUrl: https://cdn.prod.website-files.com/6899a2d38f2bb0c0bb832ba8/693858903bc741d2525af3e1_tracklabco_logo.png
  name: Tracklab
  introTitle: "**Tracklab** service status."
  introMessage: Status page which uses **real-time** data.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
