owner: tracklab-tech
repo: status

sites:
  - name: Application
    url: https://app.tracklab.co/api/
  - name: Product API
    url: https://app.tracklab.co
  - name: Website
    url: https://www.tracklab.co
    
assignees:
  - rimiti
  - nicolasfhenry
  - quentinfapdepr
  - paulgr-tracklab
  - jgourdin
  - doristlab
  - antoniotracklab
  - alicehjoedbi

status-website:
  cname: status.tracklab.co
  logoUrl: https://cdn.prod.website-files.com/6899a2d38f2bb0c0bb832ba8/693858903bc741d2525af3e1_tracklabco_logo.png
  name: Tracklab
  introTitle: "**Tracklab** service status."
  introMessage: Status page which uses **real-time** data.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
